name: My Workflow
on: push
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run a script
        run: python my_script.py
        env:
          MY_SECRET_KEY: ${{ secrets.MY_SECRET_KEY }}
